"""SMTP send + IMAP polling for review replies."""

import email as _email_module
import imaplib
import re
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText

import aiosmtplib
import anthropic
from jinja2 import Environment, BaseLoader
from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from app.config import settings
from app.models import AppSetting


# ── Jinja2 email template ──────────────────────────────────────────────────────

EMAIL_TEMPLATE = """
<!DOCTYPE html>
<html>
<head>
  <style>
    body { font-family: Arial, sans-serif; color: #333; max-width: 800px; margin: 0 auto; padding: 20px; }
    .header { background: #0077b5; color: white; padding: 20px; border-radius: 8px 8px 0 0; }
    .content { background: #f9f9f9; padding: 20px; border: 1px solid #ddd; }
    .preview-box { background: #fff; border-left: 4px solid #0077b5; padding: 15px; margin: 15px 0; }
    .action-box { background: #e8f4fd; padding: 15px; border-radius: 8px; margin: 20px 0; }
    .btn { display: inline-block; background: #0077b5; color: white; padding: 10px 20px;
           border-radius: 5px; text-decoration: none; margin: 5px; }
    pre { background: #f4f4f4; padding: 10px; overflow-x: auto; font-size: 12px; }
    code { font-family: monospace; }
    .footer { color: #888; font-size: 12px; padding: 15px; text-align: center; }
  </style>
</head>
<body>
  <div class="header">
    <h2>📝 LinkedIn Blog Draft Ready for Review</h2>
    {% if revision_number %}
    <p>Revision #{{ revision_number }}</p>
    {% endif %}
  </div>
  <div class="content">
    <h3>{{ blog_title }}</h3>

    <div class="action-box">
      <strong>To approve:</strong> Reply with <code>ok</code> or <code>approve</code> or <code>looks good</code><br>
      <strong>To request changes:</strong> Reply with your feedback/instructions
    </div>

    <p><a href="{{ preview_url }}" class="btn">View Full Preview →</a></p>

    <h4>LinkedIn Post Preview:</h4>
    <div class="preview-box">
      <pre>{{ linkedin_post }}</pre>
    </div>

    <h4>Full Blog Content (Markdown):</h4>
    <div class="preview-box">
      <pre>{{ content_preview }}</pre>
    </div>

    {% if content_truncated %}
    <p><em>Content truncated for email. <a href="{{ preview_url }}">View full blog →</a></em></p>
    {% endif %}
  </div>
  <div class="footer">
    Blog ID: {{ blog_id }} | Generated by LinkedIn Post Master
  </div>
</body>
</html>
"""

_jinja_env = Environment(loader=BaseLoader())
_template = _jinja_env.from_string(EMAIL_TEMPLATE)


async def _get_setting(db: AsyncSession, key: str, default: str = "") -> str:
    result = await db.execute(select(AppSetting).where(AppSetting.key == key))
    row = result.scalar_one_or_none()
    return row.value if row else default


async def send_review_email(
    to_email: str,
    blog_id: int,
    blog_title: str,
    content_markdown: str,
    linkedin_post: str,
    preview_url: str,
    db: AsyncSession,
    revision_number: int | None = None,
) -> str:
    """Send the blog draft to the reviewer. Returns the Message-ID header."""

    smtp_host = await _get_setting(db, "smtp_host")
    smtp_port = int(await _get_setting(db, "smtp_port", "587"))
    smtp_user = await _get_setting(db, "smtp_user")
    smtp_password = await _get_setting(db, "smtp_password")
    from_email = await _get_setting(db, "from_email", smtp_user)

    if not all([smtp_host, smtp_user, smtp_password, to_email]):
        raise ValueError("Email settings incomplete — configure SMTP in Settings")

    content_preview = content_markdown[:3000]
    content_truncated = len(content_markdown) > 3000

    subject = f"[Review] LinkedIn Blog Draft: {blog_title}"
    if revision_number:
        subject = f"[Review - Revision #{revision_number}] {blog_title}"

    html_body = _template.render(
        blog_title=blog_title,
        blog_id=blog_id,
        linkedin_post=linkedin_post,
        content_preview=content_preview,
        content_truncated=content_truncated,
        preview_url=preview_url,
        revision_number=revision_number,
    )

    msg = MIMEMultipart("alternative")
    msg["Subject"] = subject
    msg["From"] = from_email
    msg["To"] = to_email
    msg.attach(MIMEText(html_body, "html"))

    await aiosmtplib.send(
        msg,
        hostname=smtp_host,
        port=smtp_port,
        username=smtp_user,
        password=smtp_password,
        start_tls=True,
    )

    return msg.get("Message-ID", f"<blog-{blog_id}@linkedin-post-master>")


def poll_for_replies(
    imap_host: str,
    imap_port: int,
    imap_user: str,
    imap_password: str,
    pending_blogs: list[tuple[int, str, str]],  # (blog_id, message_id, review_email)
) -> list[tuple[int, str]]:
    """Synchronous IMAP poll. Returns list of (blog_id, reply_body)."""

    results = []

    try:
        imap = imaplib.IMAP4_SSL(imap_host, imap_port)
        imap.login(imap_user, imap_password)
        imap.select("INBOX")

        for blog_id, message_id, _review_email in pending_blogs:
            # Search for emails that reference the sent message
            clean_id = message_id.strip("<>")
            status, data = imap.search(None, f'(HEADER References "{clean_id}")')
            if status != "OK":
                # Try searching by subject too
                continue

            email_ids = data[0].split()
            if not email_ids:
                continue

            # Get the most recent reply
            latest = email_ids[-1]
            status2, msg_data = imap.fetch(latest, "(RFC822)")
            if status2 != "OK":
                continue

            raw = msg_data[0][1]
            parsed = _email_module.message_from_bytes(raw)
            body = _extract_body(parsed)
            if body:
                results.append((blog_id, body))

        imap.close()
        imap.logout()

    except Exception:
        pass

    return results


def _extract_body(msg) -> str:
    """Extract plain text body from email message."""
    if msg.is_multipart():
        for part in msg.walk():
            ct = part.get_content_type()
            if ct == "text/plain":
                payload = part.get_payload(decode=True)
                if payload:
                    return payload.decode("utf-8", errors="ignore")
    else:
        payload = msg.get_payload(decode=True)
        if payload:
            return payload.decode("utf-8", errors="ignore")
    return ""


async def classify_reply(reply_text: str) -> dict:
    """Ask Claude if the reply is an approval or a revision request."""

    client = anthropic.AsyncAnthropic(api_key=settings.anthropic_api_key)

    prompt = f"""Classify this email reply to a LinkedIn blog draft review:

Reply:
---
{reply_text[:1000]}
---

Respond with JSON only:
{{
  "action": "approve" | "revise",
  "changes": "extracted change instructions if action=revise, else empty string"
}}

"approve" if the reply says: ok, approve, looks good, publish it, go ahead, perfect, great, yes, sure.
"revise" for anything else (feedback, suggestions, corrections)."""

    msg = await client.messages.create(
        model="claude-haiku-4-5-20251001",
        max_tokens=300,
        messages=[{"role": "user", "content": prompt}],
    )

    import json

    json_match = re.search(r"\{[\s\S]+\}", msg.content[0].text)
    if json_match:
        try:
            return json.loads(json_match.group())
        except json.JSONDecodeError:
            pass

    return {"action": "revise", "changes": reply_text}
